\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{}
  \pretitle{\vspace{\droptitle}}
  \posttitle{}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


\begin{document}

\section{Statistical Inference Course
Project}\label{statistical-inference-course-project}

Author: Dale Hunscher

Creation Date: Friday, 27 April 2018

\subsection{Part 1: Simulation
Exercise}\label{part-1-simulation-exercise}

\subsubsection{Overview}\label{overview}

\begin{quote}
In this part of the project, you will investigate the exponential
distribution in R and compare it with the Central Limit Theorem. The
exponential distribution can be simulated in R with rexp(n, lambda)
where lambda is the rate parameter. The mean of exponential distribution
is 1/lambda and the standard deviation is also 1/lambda. Set lambda =
0.2 for all of the simulations. You will investigate the distribution of
averages of 40 exponentials. Note that you will need to do a thousand
simulations.
\end{quote}

We'll compare sample mean and variance with their theorical values. Then
we will use histograms to do a visual comparison of the sample
distribution with the narmal paradigm.

\subsubsection{Setup}\label{setup}

First we set our working directory and load libraries:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"/Users/dalehunscher/Dropbox/Coursera/Statistical_Inference/project"}\NormalTok{)}

\KeywordTok{library}\NormalTok{(knitr) }
\KeywordTok{library}\NormalTok{(graphics)}
\KeywordTok{library}\NormalTok{(datasets)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Next we set the random seed so our project results will be reproducible.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{48103}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Set the variables we'll need based on the project instructions:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nsamples <-}\StringTok{ }\DecValTok{1000} \CommentTok{# dim of mns}
\NormalTok{n <-}\StringTok{ }\DecValTok{40} \CommentTok{# n for each sample mean}
\NormalTok{lambda <-}\StringTok{ }\FloatTok{0.2} \CommentTok{# exponential rate}
\end{Highlighting}
\end{Shaded}

\subsubsection{Explorations Part One: Comparing Sample and
Theory}\label{explorations-part-one-comparing-sample-and-theory}

Compute the exponential sample data set, and then the sample and
theoretical means and standard deviations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{expo.means <-}\StringTok{ }\OtherTok{NULL}\NormalTok{; }\ControlFlowTok{for}\NormalTok{ ( i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{nsamples) \{ expo.means =}\StringTok{ }\KeywordTok{c}\NormalTok{(expo.means, }\KeywordTok{mean}\NormalTok{(}\KeywordTok{rexp}\NormalTok{(n,lambda)))\}}

\NormalTok{theoretical.mean <-}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{lambda}
\NormalTok{expo.mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(expo.means)}

\NormalTok{expo.var <-}\StringTok{ }\KeywordTok{var}\NormalTok{(expo.means)}
\NormalTok{theoretical.var <-}\StringTok{ }\NormalTok{((}\DecValTok{1}\OperatorTok{/}\NormalTok{lambda)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))}\OperatorTok{^}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

Comparing means: first the sample and theoretical means\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{expo.mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.032989
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{theoretical.mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

\ldots{}and the sample and theoretical variances\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{expo.var}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6276361
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{theoretical.var}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.625
\end{verbatim}

The sample and theoretical values are quite close, as we can see.

\subsubsection{Explorations Part Two: A Visual
Comparison}\label{explorations-part-two-a-visual-comparison}

A histogram shows the distribution of the sample means:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(expo.means,}\DataTypeTok{breaks=}\DecValTok{50}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{StatisticalInferenceCourseProject_files/figure-latex/unnamed-chunk-7-1.pdf}

For comparison purposes, we'll compute the means of a pseudo-random
sample drawn from the normal distribution and show a histogram. We'll up
the sample ``n'' and number of samples to ensure it's close to the
paradigm for a normal distribution.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\DecValTok{100}
\NormalTok{nsamples <-}\StringTok{ }\DecValTok{10000}

\NormalTok{norm.means <-}\StringTok{ }\OtherTok{NULL}\NormalTok{; }\ControlFlowTok{for}\NormalTok{ ( i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{nsamples) \{ norm.means =}\StringTok{ }\KeywordTok{c}\NormalTok{(norm.means, }\KeywordTok{mean}\NormalTok{(}\KeywordTok{rnorm}\NormalTok{(n)))\}}
\KeywordTok{hist}\NormalTok{(norm.means,}\DataTypeTok{breaks=}\DecValTok{50}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{StatisticalInferenceCourseProject_files/figure-latex/unnamed-chunk-8-1.pdf}

We can see that even a set of means of relatively small sample data sets
drawn from the exponential distribution is close to the normal paradigm.

\subsection{Part 2: Tooth Growth
Analysis}\label{part-2-tooth-growth-analysis}

\subsubsection{Overview}\label{overview-1}

We will be investigating the ToothGrowth data set from the R datasets
package.

The official description says:

\begin{quote}
\emph{The response is the length of odontoblasts (cells responsible for
tooth growth) in 60 guinea pigs. Each animal received one of three dose
levels of vitamin C (0.5, 1, and 2 mg/day) by one of two delivery
methods, orange juice or ascorbic acid (a form of vitamin C and coded as
VC).}
\end{quote}

Dietary supplements cost money. They also carry the risk of side
effects, the likelihood of the occurrence of which typically increases
as dosage increases.

We'll start by getting familiar with the data set, using exploratory
statistical techniques. Then we posit some hypotheses with respect to
the effects of choice of dietary supplement and dosage level.

Finally we'll summarize the conclusions we can draw from our
investigation.

\subsubsection{Setup}\label{setup-1}

Let's intialize some variables we'll be using later on.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# load the data set into a transient variable}

\NormalTok{tooth <-}\StringTok{ }\NormalTok{ToothGrowth}

\NormalTok{oj.group <-}\StringTok{ }\NormalTok{tooth[tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "OJ"}\NormalTok{,}\KeywordTok{c}\NormalTok{(}\StringTok{"len"}\NormalTok{,}\StringTok{"dose"}\NormalTok{)]}
\NormalTok{vc.group <-}\StringTok{ }\NormalTok{tooth[tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "VC"}\NormalTok{,}\KeywordTok{c}\NormalTok{(}\StringTok{"len"}\NormalTok{,}\StringTok{"dose"}\NormalTok{)]}

\NormalTok{doses <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\FloatTok{0.5}\NormalTok{,}\FloatTok{1.0}\NormalTok{,}\FloatTok{2.0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Exploratory Analysis}\label{exploratory-analysis}

Now we'll produce a summary of the data set and see what we can learn
from it.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(tooth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       len        supp         dose      
##  Min.   : 4.20   OJ:30   Min.   :0.500  
##  1st Qu.:13.07   VC:30   1st Qu.:0.500  
##  Median :19.25           Median :1.000  
##  Mean   :18.81           Mean   :1.167  
##  3rd Qu.:25.27           3rd Qu.:2.000  
##  Max.   :33.90           Max.   :2.000
\end{verbatim}

We have 60 data points. 30 are associated with the supp (dietary
supplement) factor ``OJ'' (referring to ascorbic acid in orange juice
form), and the remaining 30 with the supp factor ``VC'' (referring to
ascorbic acid - Vitamin C - in pure chemical form). Each row represents
a tooth length measurement (len column), a dietary supplement (supp
column), and a dosage (dose column)

Now let's do a box plot of the data set and see what we can learn from
that.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(len}\OperatorTok{~}\NormalTok{supp}\OperatorTok{*}\NormalTok{dose, }
        \DataTypeTok{data =}\NormalTok{ tooth, }
        \DataTypeTok{col=}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"yellow1"}\NormalTok{,}\StringTok{"palegreen1"}\NormalTok{)),}
        \CommentTok{#horizontal = TRUE,}
        \DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(}\StringTok{"Effects of Dietary Supplements }\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
                     \StringTok{"on Tooth Growth at Various Dosages"}\NormalTok{), }
        \DataTypeTok{xlab =} \StringTok{"Dietary Supplement versus Dosage Level"}\NormalTok{,}
        \DataTypeTok{ylab =} \StringTok{"Tooth Length"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{StatisticalInferenceCourseProject_files/figure-latex/unnamed-chunk-11-1.pdf}

\emph{In a box plot, the dotted-line ``whiskers'' represent the range of
data values; the colored boxes represent the two quartiles between 25\%
and 75\%, the middle 50\% of the values; and the solid line dividing the
colored box shows the median point in the value range.}

From this chart, we see that orange juice (OJ) appears to be more
effective at stimulating tooth growth at 0.5 and 1.0 mg/day, though in
both cases it has wider value ranges than ascorbic acid (VC). At the 2.0
dosage level, the two supplements are much closer in their effects.

Another observation of interest is that the orange juice boxes for
dosages of 1.0 and 2.0 mg/day overlap. We will want to look closely at
these to find out whether or not the higher dose is significantly more
effective. If not, the data may suggest that the lower dose is
preferable, whether in terms of lower cost or reduced probability of
side effects from the supplement.

We will need to do a deeper analysis to compare the two supplements at
the three dosage levels, to provide more information to support any
decision-making with respect to supplement and dosage level selection.
To do this analysis, we will test some hypotheses against the data set.

\subsubsection{Hypothesis Testing: Does Type of Supplement
Matter?}\label{hypothesis-testing-does-type-of-supplement-matter}

We choose to use the Student's T-test statistic because the sample
groups are small and the statistic is relatively robust with respect to
the normalcy of the data. However, we are NOT making an assumption that
the variances are approximately equal. The confidence intervals in the
box plot imply considerable differences in variance

Our null hypothesis is that the two groups, OJ and VC, are the same at
any given dosage level. Because the Tooth Growth chart above appears to
show that OJ is more effective than VC, our alternative hypothesis is
that the mean of the OJ group is significantly greater than the mean of
the VC group with a confidence of 95\%.

We will do three separate analyses to test the significance of the
difference between the two treatments at each dosage level.

\paragraph{Dosage = 0.5 mg/day}\label{dosage-0.5-mgday}

Difference beween the group means (positive value shows that OJ mean is
greater than VC mean):

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{0.5}\NormalTok{)])}\OperatorTok{-}\KeywordTok{mean}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{0.5}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.25
\end{verbatim}

Orange juice appears to have a significant advantage over pure ascorbic
acid, based both on the large difference in means and eyeballing the
Tooth Growth chart.

T-Test of the alternative hypothesis that OJ mean significantly greater
than VC mean:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result <-}\StringTok{ }\KeywordTok{t.test}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{0.5}\NormalTok{)],vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{0.5}\NormalTok{)],}\DataTypeTok{alternative=}\StringTok{"greater"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

P-value is 0.0031793\\
Upper limit of rejection region:\\
2.3460403

The mean of 5.25 is greater than the upper limit of the rejection region
at 95\% confidence level, so we can reject the null hypothesis. At a
dose of 0.5 mg/day, ascorbic acid via orange juice is significantly more
effective than pure ascorbic acid alone.

\paragraph{Dosage = 1.0 mg/day}\label{dosage-1.0-mgday}

Difference beween the group means (positive value shows that OJ mean is
greater than VC mean):

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{1.0}\NormalTok{)])}\OperatorTok{-}\KeywordTok{mean}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{1.0}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.93
\end{verbatim}

Orange juice still appears to have a significant advantage over pure
ascorbic acid, based both on the large difference in means and
eyeballing the Tooth Growth chart.

T-Test of the alternative hypothesis that OJ mean significantly greater
than VC mean:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result <-}\StringTok{ }\KeywordTok{t.test}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{1.0}\NormalTok{)],vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{1.0}\NormalTok{)],}\DataTypeTok{alternative=}\StringTok{"greater"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

P-value is 5.1918794\times 10\^{}\{-4\}\\
Upper limit of rejection region:\\
3.3561576

The mean of 5.93 is greater than the upper limit of the rejection region
at 95\% confidence level, so we can reject the null hypothesis. At a
dose of 1.0 mg/day, ascorbic acid via orange juice is significantly more
effective than pure ascorbic acid alone.

\paragraph{Dosage = 2.0 mg/day}\label{dosage-2.0-mgday}

Difference beween the group means (positive value shows that OJ mean is
greater than VC mean):

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{2.0}\NormalTok{)])}\OperatorTok{-}\KeywordTok{mean}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{2.0}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.08
\end{verbatim}

The difference is now close to zero (and actually leans in favor of pure
ascorbic acid, in constrast to the smaller dosages). We can reasonably
assume we will fail to reject the null hypothesis in this case, but
let's do the test to make sure.

This time we will use a two-tail test with the null hypothesis that the
difference in means is insignificant. This will test the more general
case of the two means being significantly different. If the difference
turned out to be significant, we would need to investigate more deeply
to determine which treatment was the greater.

T-Test of the alternative hypothesis that OJ mean significantly greater
than VC mean:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{result <-}\StringTok{ }\KeywordTok{t.test}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(oj.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{2.0}\NormalTok{)],vc.group}\OperatorTok{$}\NormalTok{len[}\KeywordTok{which}\NormalTok{(vc.group}\OperatorTok{$}\NormalTok{dose }\OperatorTok{==}\StringTok{ }\FloatTok{2.0}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

P-value is 0.9638516\\
Upper limit of rejection region:\\
-3.7980705 : 3.6380705

The p-value is much greater than the 95\% cutoff of 0.05, so we can
accept the null hypothesis, that the difference in means is
insignificant. The null hypothesis's posited mean of 0 and the actual
mean of the differences, \{r mean(oj.group\(len[which(oj.group\)dose ==
2.0){]})-mean(vc.group\(len[which(vc.group\)dose == 2.0){]}) \}, are
both well within the rejection region. At a dose of 2.0 mg/day, ascorbic
acid via orange juice is NOT significantly more effective than pure
ascorbic acid alone.

\subsubsection{Hypothesis Testing: Does Dosage
Matter?}\label{hypothesis-testing-does-dosage-matter}

Our analysis would be incomplete if we did not also look at the
significance of the different dosage levels under each supplement.

Why do we care? We have seen thus far that a dietary supplement of
ascorbic acid in orange juice is superior to pure ascorbic acid for
lower dosage levels (0.5 and 1.0 mg/day), but the effectiveness of the
two supplements is not significantly different at the higher dosage of
2.0 mg/day.

Let's assume that pure ascorbic acid is less expensive per milligram
than its equivalent in orange juice. The most cost-effective approach
would then be pure ascorbic acid at 2.0 mg/day -- but only if the gain
in growth rates between, for example, 1.0 and 2.0 mg/day were
significant enough to justify the increased cost.

A deeper analysis would compare the cost and benefit of the different
combinations of supplement and dosage in terms of growth rate
improvements. Perhaps guinea pig teeth are valuable in Chinese medicine,
in which case benefit will trump cost in the decision-making process.
This analysis is out of the scope of this project, since we have been
given neither the cost of supplements nor the means to evaluate the
potential sale price of guinea pig teeth.

Staying within our scope, we will look at the significance of length
gains length for each dosage level and the next higher increment in
dosage. We will do this by supplement, treating it as a potentially
confounding variable.

For each supplement, we will compare 0.5 versus 1.0 mg/day and 1.0
versus 2.0 mg/day.

Our null hypothesis throughout is that the difference between the two
dosage levels under consideration is insignificant with 95\% confidence.

\paragraph{Orange Juice (OJ)}\label{orange-juice-oj}

\subparagraph{0.5 versus 1.0 mg/day}\label{versus-1.0-mgday}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{0.5} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "OJ"}\NormalTok{],tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{1.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "OJ"}\NormalTok{])}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.784919e-05
\end{verbatim}

The p-value is less than 0.05 and positive, hence the higher dosage is
significantly more effective at stimulating tooth growth.

\subparagraph{1.0 versus 2.0 mg/day}\label{versus-2.0-mgday}

We recall from the box plot chart that there was considerable overlap
between the boxes for orange juice at these two dosages. This test will
provide insight into whether the higher dosage is actually significantly
more effective.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{1.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "OJ"}\NormalTok{],tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{2.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "OJ"}\NormalTok{])}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.03919514
\end{verbatim}

Once again, the p-value is less than 0.05 and positive, hence the higher
dosage is significantly more effective at stimulating tooth growth.

\paragraph{Pure Ascorbic Acid (VC)}\label{pure-ascorbic-acid-vc}

\subparagraph{0.5 versus 1.0 mg/day}\label{versus-1.0-mgday-1}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{0.5} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "VC"}\NormalTok{],tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{1.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "VC"}\NormalTok{])}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.811018e-07
\end{verbatim}

In this case as well, the p-value is less than 0.05 and positive, hence
the higher dosage is significantly more effective at stimulating tooth
growth.

\subparagraph{1.0 versus 2.0 mg/day}\label{versus-2.0-mgday-1}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{1.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "VC"}\NormalTok{],tooth}\OperatorTok{$}\NormalTok{len[tooth}\OperatorTok{$}\NormalTok{dose}\OperatorTok{==}\FloatTok{2.0} \OperatorTok{&}\StringTok{ }\NormalTok{tooth}\OperatorTok{$}\NormalTok{supp }\OperatorTok{==}\StringTok{ "VC"}\NormalTok{])}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.155603e-05
\end{verbatim}

And also in our final test case, the p-value is less than 0.05 and
positive, hence the higher dosage is significantly more effective at
stimulating tooth growth.

\subsubsection{Conclusions Of Tooth Growth
Analysis}\label{conclusions-of-tooth-growth-analysis}

\begin{itemize}
\item
  The higher the dosage the better in terms of stimulating tooth growth,
  regardless of supplement. For both supplements, the difference between
  each incrementally adjacent dosage pair (0.5-1.0 and 1.0-2.0 mg/day)
  is significant.
\item
  At lower dosages (0.5 and 1.0 mg/day), the performance of orange juice
  is significantly better than pure ascorbic acid. The box plot showed
  that the difference is most pronouced at the 1.0 dosage level.
\item
  At the highest dosage level tested, 2.0 mg/day, the performance of
  orange juice and pure ascorbic acid are roughly equivalent.
\end{itemize}


\end{document}
